#!/bin/bash

# Do not edit this file!

# To change authToken and owner id: 
## edit your Config Vars in heroku/app/settings and 
## restart the bot by turning the worker off and back on

echo "Creating config.json..."
cd /home/shell-bot
cat > config.json << EOF
{
    "authToken": "5309511285:AAG6Bssnf6jKnuwihCfbms2Gt3iBiIA7Nfs",
    "owner": 1137436016
}
EOF
echo "Done."

echo "Starting Bot..."
node server
